# Generated by Django 5.1.1 on 2024-10-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='data_nascimento',
        ),
        migrations.AddField(
            model_name='paciente',
            name='Disponibilidade',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='atendimento',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default=11, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='atendimento_Tipo_Tempo_Motivo',
            field=models.CharField(default=11, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='contato_de_emergência',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='data_de_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='escolaridade',
            field=models.CharField(choices=[('Fundamental', 'Fundamental'), ('Médio', 'Médio'), ('Superior Completo', 'Superior Completo'), ('Superior incompleto', 'Superior incompleto'), ('Pós-Grauação', 'Pós-Graduação'), ('Mestrado', 'Mestrado'), ('Dotourado', 'Dotourado')], default=11, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='estado_Civil',
            field=models.CharField(choices=[('Não Informado', 'Não Informado'), ('Casado(a)', 'Casado(a)'), ('Solteiro(a)', 'Solteiro(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Viúvo(a)', 'Viúvo(a)')], default=11, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='filhos',
            field=models.CharField(choices=[('S', 'Sim'), ('F', 'Não')], default=11, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='filhos_Quantidade',
            field=models.CharField(default=11, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='motivo_e_objetivo',
            field=models.CharField(default=11, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='profissão',
            field=models.CharField(default=11, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='qual_Medicamento',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='rede_de_apoio',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='religião',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='toma_Algum_Medicamento',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='trabalha_no_momento',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=10),
        ),
    ]
