# Generated by Django 5.1.1 on 2024-11-02 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente'),
        ),
    ]
