# Generated by Django 5.1.1 on 2024-11-05 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0009_alter_paciente_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='pacientes.paciente'),
        ),
    ]
