# Generated by Django 5.1.1 on 2024-11-05 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0010_alter_pagamento_paciente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='data_de_nascimento',
            new_name='data_nascimento',
        ),
    ]
