# Generated by Django 5.1.1 on 2025-09-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0011_rename_data_de_nascimento_paciente_data_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='atendimento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='atendimento_Tipo_Tempo_Motivo',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='filhos',
        ),
        migrations.AddField(
            model_name='paciente',
            name='atendimento_anterior',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=10, verbose_name='Teve atendimento anterior?'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cpf_responsavel',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF do responsável'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='eh_menor_tutelado',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=10, verbose_name='É menor de idade/tutelado?'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='email_responsavel',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do responsável'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='endereco_responsavel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço do responsável'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='grau_parentesco',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Grau de parentesco/relação'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='motivo_procura_queixa',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Motivo da Procura/Queixa'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nome_responsaveis',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome dos responsáveis'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='possui_filhos',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=10, verbose_name='Possui Filhos?'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefone_alternativo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefone_responsavel',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone do responsável'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_atendimento_ofertado',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Tipo de Atendimento Ofertado'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='recibo_receita_saude',
            field=models.BooleanField(default=False, verbose_name='Recibo emitido via Receita Saúde'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='tipo_pagamento',
            field=models.CharField(choices=[('Particular', 'Particular'), ('Convênio', 'Convênio'), ('Clínica', 'Clínica')], default='Particular', max_length=20, verbose_name='Tipo de Pagamento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Disponibilidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='contato_de_emergência',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='escolaridade',
            field=models.CharField(choices=[('Sem escolaridade', 'Sem escolaridade'), ('Fundamental', 'Fundamental'), ('Médio', 'Médio'), ('Superior Completo', 'Superior Completo'), ('Superior incompleto', 'Superior incompleto'), ('Pós-Graduação', 'Pós-Graduação'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado')], max_length=255),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estado_Civil',
            field=models.CharField(choices=[('Não Informado', 'Não Informado'), ('Casado(a)', 'Casado(a)'), ('Solteiro(a)', 'Solteiro(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Viúvo(a)', 'Viúvo(a)'), ('Não se aplica', 'Não se aplica')], max_length=255),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='filhos_Quantidade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='motivo_e_objetivo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='observações',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='profissão',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='qual_Medicamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rede_de_apoio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rede de Apoio'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='religião',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='forma_pagamento',
            field=models.CharField(choices=[('Pix', 'Pix'), ('Dinheiro', 'Dinheiro'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão de Débito', 'Cartão de Débito'), ('Convênio', 'Convênio'), ('Clínica', 'Clínica')], max_length=20),
        ),
    ]
